#!/usr/bin/sh
#Local version for servo

INCL="-I include -I $NEWSERVO/include"

if test $1 = "-s"
then
	shift;
	for i in $*
	{
		cproto -s -f3 $INCL $i | egrep '^static|^#|^/'
	}
else
	for i in $*
	{
		cproto -f3 $INCL $i
	}
fi
